const actionTypes = Object.freeze({
	// App
	APP_CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

	// User
	USER_LOGIN: 'USER_LOGIN',
	USER_LOGOUT: 'USER_LOGOUT',

	// Todos
	TODOS_ADD: 'ADD',
	TODOS_UPDATE: 'UPDATE',
	TODOS_TOGGLE_COMPLETE_ALL: 'TOGGLE_COMPLETE_ALL',
	TODOS_TOGGLE_COMPLETE: 'TOGGLE_COMPLETE',
	TODOS_FILTER: 'FILTER',
	TODOS_CLEAR_COMPLETED: 'CLEAR_COMPLETED',
	TODOS_DELETE: 'DELETE',
});
export default actionTypes;
