const actionTypes = Object.freeze({
	APP: {
		CHANGE_LANGUAGE: 'CHANGE_LANGUAGE'
	},
	USER: {
		USER_LOGIN: 'USER_LOGIN'
	},
	TODOS: {
		ADD: 'ADD',
		UPDATE: 'UPDATE',
		TOGGLE_COMPLETE_ALL: 'TOGGLE_COMPLETE_ALL',
		TOGGLE_COMPLETE: 'TOGGLE_COMPLETE',
		FILTER: 'FILTER',
		CLEAR_COMPLETED: 'CLEAR_COMPLETED',
		DELETE: 'DELETE'
	}
});

export default actionTypes;
